// Generated by gencpp from file katech_msg_test_pkg/Katech_test_msg.msg
// DO NOT EDIT!


#ifndef KATECH_MSG_TEST_PKG_MESSAGE_KATECH_TEST_MSG_H
#define KATECH_MSG_TEST_PKG_MESSAGE_KATECH_TEST_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace katech_msg_test_pkg
{
template <class ContainerAllocator>
struct Katech_test_msg_
{
  typedef Katech_test_msg_<ContainerAllocator> Type;

  Katech_test_msg_()
    : velocity(0)
    , wheel(0)
    , yaw(0.0)  {
    }
  Katech_test_msg_(const ContainerAllocator& _alloc)
    : velocity(0)
    , wheel(0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _velocity_type;
  _velocity_type velocity;

   typedef int32_t _wheel_type;
  _wheel_type wheel;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Katech_test_msg_

typedef ::katech_msg_test_pkg::Katech_test_msg_<std::allocator<void> > Katech_test_msg;

typedef boost::shared_ptr< ::katech_msg_test_pkg::Katech_test_msg > Katech_test_msgPtr;
typedef boost::shared_ptr< ::katech_msg_test_pkg::Katech_test_msg const> Katech_test_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace katech_msg_test_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'katech_msg_test_pkg': ['/home/katech/catkin_ws/src/katech_msg_test_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "587936dd7ca4add6c71b58cdb7ef89ad";
  }

  static const char* value(const ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x587936dd7ca4add6ULL;
  static const uint64_t static_value2 = 0xc71b58cdb7ef89adULL;
};

template<class ContainerAllocator>
struct DataType< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "katech_msg_test_pkg/Katech_test_msg";
  }

  static const char* value(const ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 velocity\n\
int32 wheel\n\
float32 yaw\n\
";
  }

  static const char* value(const ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.wheel);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Katech_test_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::katech_msg_test_pkg::Katech_test_msg_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.velocity);
    s << indent << "wheel: ";
    Printer<int32_t>::stream(s, indent + "  ", v.wheel);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KATECH_MSG_TEST_PKG_MESSAGE_KATECH_TEST_MSG_H
