// Generated by gencpp from file test_msgs/KatechTest.msg
// DO NOT EDIT!


#ifndef TEST_MSGS_MESSAGE_KATECHTEST_H
#define TEST_MSGS_MESSAGE_KATECHTEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_msgs
{
template <class ContainerAllocator>
struct KatechTest_
{
  typedef KatechTest_<ContainerAllocator> Type;

  KatechTest_()
    : steering_wheel_angle_cmd(0)
    , steering_velocity_cmd(0)  {
    }
  KatechTest_(const ContainerAllocator& _alloc)
    : steering_wheel_angle_cmd(0)
    , steering_velocity_cmd(0)  {
  (void)_alloc;
    }



   typedef int32_t _steering_wheel_angle_cmd_type;
  _steering_wheel_angle_cmd_type steering_wheel_angle_cmd;

   typedef int32_t _steering_velocity_cmd_type;
  _steering_velocity_cmd_type steering_velocity_cmd;





  typedef boost::shared_ptr< ::test_msgs::KatechTest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_msgs::KatechTest_<ContainerAllocator> const> ConstPtr;

}; // struct KatechTest_

typedef ::test_msgs::KatechTest_<std::allocator<void> > KatechTest;

typedef boost::shared_ptr< ::test_msgs::KatechTest > KatechTestPtr;
typedef boost::shared_ptr< ::test_msgs::KatechTest const> KatechTestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_msgs::KatechTest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_msgs::KatechTest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'test_msgs': ['/home/katech/catkin_ws/src/msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_msgs::KatechTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_msgs::KatechTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msgs::KatechTest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_msgs::KatechTest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msgs::KatechTest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_msgs::KatechTest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_msgs::KatechTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d1d743ebccd40b1c19440e1aea32db4";
  }

  static const char* value(const ::test_msgs::KatechTest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d1d743ebccd40b1ULL;
  static const uint64_t static_value2 = 0xc19440e1aea32db4ULL;
};

template<class ContainerAllocator>
struct DataType< ::test_msgs::KatechTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_msgs/KatechTest";
  }

  static const char* value(const ::test_msgs::KatechTest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_msgs::KatechTest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 steering_wheel_angle_cmd\n\
int32 steering_velocity_cmd\n\
";
  }

  static const char* value(const ::test_msgs::KatechTest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_msgs::KatechTest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steering_wheel_angle_cmd);
      stream.next(m.steering_velocity_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KatechTest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_msgs::KatechTest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_msgs::KatechTest_<ContainerAllocator>& v)
  {
    s << indent << "steering_wheel_angle_cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steering_wheel_angle_cmd);
    s << indent << "steering_velocity_cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steering_velocity_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MSGS_MESSAGE_KATECHTEST_H
