// Generated by gencpp from file can_test_pkg/KatechSonata.msg
// DO NOT EDIT!


#ifndef CAN_TEST_PKG_MESSAGE_KATECHSONATA_H
#define CAN_TEST_PKG_MESSAGE_KATECHSONATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace can_test_pkg
{
template <class ContainerAllocator>
struct KatechSonata_
{
  typedef KatechSonata_<ContainerAllocator> Type;

  KatechSonata_()
    : velocity(0)  {
    }
  KatechSonata_(const ContainerAllocator& _alloc)
    : velocity(0)  {
  (void)_alloc;
    }



   typedef int32_t _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::can_test_pkg::KatechSonata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::can_test_pkg::KatechSonata_<ContainerAllocator> const> ConstPtr;

}; // struct KatechSonata_

typedef ::can_test_pkg::KatechSonata_<std::allocator<void> > KatechSonata;

typedef boost::shared_ptr< ::can_test_pkg::KatechSonata > KatechSonataPtr;
typedef boost::shared_ptr< ::can_test_pkg::KatechSonata const> KatechSonataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::can_test_pkg::KatechSonata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::can_test_pkg::KatechSonata_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace can_test_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'can_test_pkg': ['/home/katech/catkin_ws/src/can_test_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::can_test_pkg::KatechSonata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::can_test_pkg::KatechSonata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::can_test_pkg::KatechSonata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1221446a6cb55fc620353cce70eed4a";
  }

  static const char* value(const ::can_test_pkg::KatechSonata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1221446a6cb55fcULL;
  static const uint64_t static_value2 = 0x620353cce70eed4aULL;
};

template<class ContainerAllocator>
struct DataType< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "can_test_pkg/KatechSonata";
  }

  static const char* value(const ::can_test_pkg::KatechSonata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 velocity\n\
";
  }

  static const char* value(const ::can_test_pkg::KatechSonata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KatechSonata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::can_test_pkg::KatechSonata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::can_test_pkg::KatechSonata_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAN_TEST_PKG_MESSAGE_KATECHSONATA_H
